CUDA_VISIBLE_DEVICES=2 python ../train.py \
--config_file ../configs/ship/vit_base.yml \
SOLVER.EVAL_PERIOD 20 \
SOLVER.IMS_PER_BATCH 48 \
SOLVER.MAX_EPOCHS 200 \
OUTPUT_DIR ./logs/ \
DATASETS.NAMES "('ShipReID2400')" \
MODEL.PART_H 16 \
MODEL.PART_W 4 \
MODEL.ID_LOSS_WEIGHT 0.5 \
MODEL.TRIPLET_LOSS_WEIGHT 5.0 \
MODEL.PART_ID_LOSS_WEIGHT 0.5 \
MODEL.PART_TRIPLET_LOSS_WEIGHT 5.0 \
MODEL.TOKEN_CONTRAST_LOSS_WEIGHT 10.0 \
MODEL.PART_RATIO 0.6 \
MODEL.TOKEN_CONTRAST_TYPE 'triplet' \
MODEL.NO_TOKEN_MARGIN False \
SOLVER.TOKEN_MARGIN 0.3