MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.5
  PART_ID_LOSS_WEIGHT : 0.5
  TRIPLET_LOSS_WEIGHT : 1.0
  PART_TRIPLET_LOSS_WEIGHT : 1.0
  # SIE_CAMERA: True
  # SIE_COE : 1.0
  
INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  IMS_PER_BATCH: 6
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.0000275
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY:  0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  LARGE_FC_LR: False
  MAX_EPOCHS: 120
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 50
  EVAL_PERIOD: 20
  BIAS_LR_FACTOR: 2
  
  STEPS: [30, 50]
  GAMMA: 0.1
  
TEST:
  EVAL: True
  IMS_PER_BATCH: 48
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

DATASETS:
  NAMES: ('ShipReID2400')
  ROOT_DIR: ('/media/data1/hrk/code/reid/datasets/ship')
OUTPUT_DIR: './logs/'

#   NAMES: ('dukemtmc')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

#   NAMES: ('occ_duke')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

#   NAMES: ('msmt17')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

# CUDA_VISIBLE_DEVICES=2 python train.py --config_file configs/person/vit_base.yml